/* This file is part of the jQuery wordStats plugin
 * Copyright (C) 2007 Jean-Francois Hovinne - http://www.hovinne.com/
 * Dual licensed under the MIT (MIT-license.txt)
 * and GPL (GPL-license.txt) licenses.
 */

jQuery.wordStats.stopWords = {
    'about': true,
    'after': true,
    'ago': true,
    'all': true,
    'also': true,
    'an': true,
    'and': true,
    'any': true,
    'are': true,
    'as': true,
    'at': true,
    'be': true,
    'been': true,
    'before': true,
    'both': true,
    'but': true,
    'by': true,
    'can': true,
    'did': true,
    'do': true,
    'does': true,
    'done': true,
    'edit': true,
    'even': true,
    'every': true,
    'for': true,
    'from': true,
    'had': true,
    'has': true,
    'have': true,
    'he': true,
    'here': true,
    'him': true,
    'his': true,
    'however': true,
    'if': true,
    'in': true,
    'into': true,
    'is': true,
    'it': true,
    'its': true,
    'less': true,
    'many': true,
    'may': true,
    'more': true,
    'most': true,
    'much': true,
    'my': true,
    'no': true,
    'not': true,
    'often': true,
    'quote': true,
    'of': true,
    'on': true,
    'one': true,
    'only': true,
    'or': true,
    'other': true,
    'our': true,
    'out': true,
    're': true,
    'says': true,
    'she': true,
    'so': true,
    'some': true,
    'soon': true,
    'such': true,
    'than': true,
    'that': true,
    'the': true,
    'their': true,
    'them': true,
    'then': true,
    'there': true,
    'these': true,
    'they': true,
    'this': true,
    'those': true,
    'though': true,
    'through': true,
    'to': true,
    'under': true,
    'use': true,
    'using': true,
    've': true,
    'was': true,
    'we': true,
    'were': true,
    'what': true,
    'where': true,
    'when': true,
    'whether': true,
    'which': true,
    'while': true,
    'who': true,
    'whom': true,
    'with': true,
    'within': true,
    'you': true,
    'your': true
};

/*
jQuery.wordStats.testChar = function(c) {
    return(c >= 97 && c <= 122);
};*/
